### PR TITLE
Add new predefined DNS strings to language file.

### PR DESCRIPTION
**Pull request by d3fz**
Add new predefined DNS strings to basic.js PT-BR language file.

### CODE REVIEW

**Comment by lantis1008** [comment]
Merged

**Comment by d3fz** [comment]
Great.

Would you like me to update the other languages as well, or just leave as it is ?

**Comment by lantis1008** [comment]
If you are familiar with the languages please feel free. I guess there isn't really much to translate, they are product names.
It would be appreciated :+1:

**Comment by d3fz** [comment]
Alright, will do.

**Pull request merged**
